version: "3.3"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:0.9.1
    ports:
      - "4572:4572"
      - "4576:4576"
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=ap-northeast-1
      - DOCKER_HOST=unix:///var/run/docker.sock
