AWSTemplateFormatVersion: "2010-09-09"
Description: CFn Artifacts Bucket

Parameters:
  Env:
    Type: AWS::SSM::Parameter::Value<String>
    Default: EnvironName
  DefaultSlackIncommingWebhookUrl:
    Type: AWS::SSM::Parameter::Value<String>
    Default: ArtilfSlackWebhookUrl

Resources:
  BaseResourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/01_base_resource.yml

  AlertResourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/03_alert_resource.yml
      Parameters:
        Env: !Ref Env
        DefaultSlackIncommingWebhookUrl: !Ref DefaultSlackIncommingWebhookUrl
        CommonLayerArn: !GetAtt BaseResourceStack.Outputs.CommonLayerArn

  LogParseResourceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: src/04_log_parse_resource.yml
      Parameters:
        Env: !Ref Env
        CommonLayerArn: !GetAtt BaseResourceStack.Outputs.CommonLayerArn
        ErrorAlertSNSTopicArn: !GetAtt AlertResourceStack.Outputs.ErrorAlertSNSTopicArn
        PublishTargetSNSTopicArn: !GetAtt AlertResourceStack.Outputs.LogAlertSNSTopicArn
