version: 2

references:
  primary_containers: &primary_containers
    docker:
      - image: circleci/python:3.6.8

  test_containers: &test_containers
    docker:
      - image: circleci/python:3.6.8
      - image: localstack/localstack:0.9.1
        environment:
          SERVICES: s3

  install_dependencies: &install_dependencies
    run:
      name: Install Dependencies
      command: |
        if [[ ! -d .venv ]]; then
          python -m venv .venv
          source .venv/bin/activate
          pip install pipenv==$ARTILF_PIPENV_VERSION
          pipenv install
        fi

  save_dependencies: &save_dependencies
    save_cache:
      paths:
        - .venv
      key: dependencies-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}

  restore_dependencies: &restore_dependencies
    restore_cache:
      keys:
        - dependencies-{{ .Branch }}-{{ checksum "Pipfile" }}-{{ checksum "Pipfile.lock" }}

  notify_start_to_slack: &notify_start_to_slack
    run:
      name: Notify Start to Slack
      command: ./notify.sh -s

  notify_success_to_slack: &notify_success_to_slack
    run:
      name: Notify Success to Slack
      command: ./notify.sh -e

  notify_failed_to_slack: &notify_failed_to_slack
    run:
      name: Notify Failed to Slack
      command: ./notify.sh -f
      when: on_fail

jobs:
  test_unit:
    <<: *primary_containers
    steps:
      - checkout
      - <<: *notify_start_to_slack
      - <<: *restore_dependencies
      - <<: *install_dependencies
      - <<: *save_dependencies
      - run:
          name: raw account
          command: |
            source .venv/bin/activate

            aws sts get-caller-identity
      - run:
          name: development
          command: |
            source .venv/bin/activate

            eval "$(./guess.sh -e development -a)"
            aws sts get-caller-identity
      - run:
          name: production
          command: |
            source .venv/bin/activate

            eval "$(./guess.sh -e production -a)"
            aws sts get-caller-identity
      - <<: *notify_success_to_slack
      - <<: *notify_failed_to_slack

  test_integration:
    <<: *primary_containers
    steps:
      - checkout
      - <<: *notify_start_to_slack
      - <<: *restore_dependencies
      - <<: *install_dependencies
      - <<: *save_dependencies
      - <<: *notify_success_to_slack
      - <<: *notify_failed_to_slack

  deploy_development:
    <<: *primary_containers
    steps:
      - checkout
      - <<: *notify_start_to_slack
      - <<: *restore_dependencies
      - <<: *install_dependencies
      - <<: *save_dependencies
      - run:
          name: deploy
          command: |
            source .venv/bin/activate

            eval "$(./guess.sh -e development -a)"
            make deploy
      - store_artifacts:
          path: packaged_template.yml
      - <<: *notify_success_to_slack
      - <<: *notify_failed_to_slack

  test_e2e_development:
    <<: *primary_containers
    steps:
      - checkout
      - <<: *notify_start_to_slack
      - <<: *restore_dependencies
      - <<: *install_dependencies
      - <<: *save_dependencies
      - run:
          name: test e2e on development
          command: echo e2e
      - <<: *notify_success_to_slack
      - <<: *notify_failed_to_slack

  deploy_production:
    <<: *primary_containers
    steps:
      - checkout
      - <<: *notify_start_to_slack
      - <<: *restore_dependencies
      - <<: *install_dependencies
      - <<: *save_dependencies
      - run:
          name: deploy
          command: |
            source .venv/bin/activate

            eval "$(./guess.sh -e production -a)"
            make deploy
      - store_artifacts:
          path: packaged_template.yml
      - <<: *notify_success_to_slack
      - <<: *notify_failed_to_slack

  test_e2e_production:
    <<: *primary_containers
    steps:
      - checkout
      - <<: *notify_start_to_slack
      - <<: *restore_dependencies
      - <<: *install_dependencies
      - <<: *save_dependencies
      - run:
          name: test e2e production
          command: echo e2e
      - <<: *notify_success_to_slack
      - <<: *notify_failed_to_slack

workflows:
  version: 2
  artilf_api_development:
    jobs:
      - test_unit
      - test_integration:
          requires:
            - test_unit

  artilf_api_production:
    jobs:
      - test_unit:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - test_integration:
          requires:
            - test_unit
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy_development:
          requires:
            - test_integration
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - test_e2e_development:
          requires:
            - deploy_development
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - approve_deploy_production:
          type: approval
          requires:
            - test_e2e_development
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - deploy_production:
          requires:
            - approve_deploy_production
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - test_e2e_production:
          requires:
            - deploy_production
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
