AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: artilf base resources

Resources:
  CommonLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: 01_base_resource/common
      RetentionPolicy: Retain
      CompatibleRuntimes:
        - python3.6

Outputs:
  CommonLayerArn:
    Value: !Ref CommonLayer
