AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: alert resources

Parameters:
  Env:
    Type: String

  DefaultSlackIncommingWebhookUrl:
    Type: String

  CommonLayerArn:
    Type: String

Globals:
  Function:
    Runtime: python3.6
    Timeout: 30
    MemorySize: 128
    AutoPublishAlias: !Ref Env
    Environment:
      Variables:
        AWS_ENV: !Ref Env
    Layers:
      - !Ref CommonLayerArn


Resources:
  SlackNotifierApplication:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: arn:aws:serverlessrepo:us-east-1:355081757265:applications/sar-aws-sns-to-slack
        SemanticVersion: 1.2.0
      Parameters:
        DefaultSlackIncommingWebhookUrl: !Ref DefaultSlackIncommingWebhookUrl

  NotifierFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Slack通知用のSNSにログのエラー通知を投げる
      CodeUri: 03_base_resource/notifier
      Handler: index.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSNSFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Layers:
        - !GetAtt SlackNotifierApplication.Outputs.SlackNotifierLayerArn
