AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: log parse resource

Parameters:
  LambdaLogGroupNamePrefix:
    Type: String
    Default: /aws/lambda

  Env:
    Type: String

  CommonLayerArn:
    Type: String

  ErrorAlertSNSTopicArn:
    Type: String

  LogAlertQueueUrl:
    Type: String

Globals:
  Function:
    Runtime: python3.6
    Timeout: 30
    MemorySize: 128
    AutoPublishAlias: !Ref Env
    Environment:
      Variables:
        AWS_ENV: !Ref Env
    Layers:
      - !Ref CommonLayerArn

Resources:
  S3EventQueue:
    Type: AWS::SQS::Queue

  ParserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: S3に吐かれたログデータからエラーの情報を抽出する
      CodeUri: 04_log_parse_resource/parser
      Handler: index.handler
      Policies:
        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      Environment:
        Variables:
          LOG_ALERT_QUEUE_URL: !Ref LogAlertQueueUrl
      Events:
        GetFromSQS:
          Type: SQS
          Properties:
            Queue: !GetAtt S3EventQueue.Arn
            BatchSize: 10
            Enabled: true

  ParserLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${LambdaLogGroupNamePrefix}/${ParserFunction}
      RetentionInDays: 30

  ParserErrorAlertMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "?\"\\\"levelname\\\": \\\"ERROR\\\"\""
      LogGroupName: !Ref ParserLogGroup
      MetricTransformations:
        - MetricName: !Sub ${ParserFunction}-error-alert-metric-filter-${Env}
          MetricNamespace: Custom/LogMetrics
          MetricValue: "1"

  ParserErrorAlertAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${ParserFunction}-error-alert-${Env}
      AlarmActions:
        - !Ref ErrorAlertSNSTopicArn
      ActionsEnabled: true
      MetricName: !Sub ${ParserFunction}-error-alert-metric-filter-${Env}
      Namespace: Custom/LogMetrics
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1.0
      ComparisonOperator: GreaterThanOrEqualToThreshold
